version: "3"

services:
  backend:
    build: ./shopping_cart_backend
    restart: always
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=latha123
      - DB_NAME=shopping_cart
    depends_on:
      - mysql
    ports:
      - "3400:3400"

  frontend:
    build: ./shopping_cart_frontend
    restart: always
    ports:
      - "3000:3000"

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: latha123
      MYSQL_DATABASE: shopping_cart
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  mysql-data:
